import Image from "next/image";
import Link from "next/link";
import { format } from "date-fns";
import { Home, Clock, Shield } from "lucide-react";
import { prisma } from "@/lib/db";
import { PassportViewer, type PassportData } from "@/components/passport/passport-viewer";

interface PageProps {
  params: Promise<{ token: string }>;
}

export async function generateMetadata({ params }: PageProps) {
  const { token } = await params;

  const passport = await prisma.homePassport.findUnique({
    where: { shareToken: token },
    include: {
      home: { select: { name: true } },
    },
  });

  if (!passport || !passport.isPublic) {
    return { title: "Passport Not Found | HomeOS" };
  }

  if (passport.shareExpiresAt && new Date(passport.shareExpiresAt) < new Date()) {
    return { title: "Passport Expired | HomeOS" };
  }

  return {
    title: `${passport.home.name} - Home Passport | HomeOS`,
    description: `Digital home passport for ${passport.home.name}. Generated by HomeOS.`,
  };
}

export default async function PublicPassportPage({ params }: PageProps) {
  const { token } = await params;

  const passport = await prisma.homePassport.findUnique({
    where: { shareToken: token },
    include: {
      home: { select: { name: true } },
    },
  });

  // Not found
  if (!passport || !passport.isPublic) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-[hsl(var(--background))] px-4">
        <div className="mx-auto max-w-md text-center">
          <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-red-100 dark:bg-red-900/30">
            <Shield className="h-8 w-8 text-red-500" />
          </div>
          <h1 className="mt-6 font-heading text-2xl font-bold">
            Passport Not Found
          </h1>
          <p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">
            This home passport link is invalid or has been revoked by the owner.
          </p>
          <Link
            href="/"
            className="mt-6 inline-flex items-center gap-2 text-sm font-medium text-teal-600 hover:text-teal-700"
          >
            <Home className="h-4 w-4" />
            Go to HomeOS
          </Link>
        </div>
      </div>
    );
  }

  // Expired
  if (passport.shareExpiresAt && new Date(passport.shareExpiresAt) < new Date()) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-[hsl(var(--background))] px-4">
        <div className="mx-auto max-w-md text-center">
          <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-amber-100 dark:bg-amber-900/30">
            <Clock className="h-8 w-8 text-amber-500" />
          </div>
          <h1 className="mt-6 font-heading text-2xl font-bold">
            Passport Expired
          </h1>
          <p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">
            This home passport link has expired. Please contact the homeowner
            for a new link.
          </p>
          <Link
            href="/"
            className="mt-6 inline-flex items-center gap-2 text-sm font-medium text-teal-600 hover:text-teal-700"
          >
            <Home className="h-4 w-4" />
            Go to HomeOS
          </Link>
        </div>
      </div>
    );
  }

  const passportData = passport.data as unknown as PassportData;

  return (
    <div className="min-h-screen bg-[hsl(var(--muted))]/30">
      {/* Header */}
      <header className="border-b border-[hsl(var(--border))] bg-[hsl(var(--background))]">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-4 sm:px-6">
          <Link href="/" className="flex items-center gap-3">
            <Image
              src="/logo.png"
              alt="HomeOS"
              width={36}
              height={36}
              className="rounded-lg shadow-sm"
            />
            <div className="flex flex-col">
              <span className="font-heading text-base font-bold leading-tight">
                HomeOS <span className="text-teal-500">AI</span>
              </span>
              <span className="text-[10px] font-medium tracking-wide text-[hsl(var(--muted-foreground))]">
                Home Passport
              </span>
            </div>
          </Link>
          <div className="text-right">
            <p className="text-sm font-medium">{passport.home.name}</p>
            {passport.generatedAt && (
              <p className="text-xs text-[hsl(var(--muted-foreground))]">
                Generated{" "}
                {format(new Date(passport.generatedAt), "MMM d, yyyy")}
              </p>
            )}
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="mx-auto max-w-5xl px-4 py-8 sm:px-6">
        <PassportViewer data={passportData} branded />
      </main>
    </div>
  );
}
