import Link from 'next/link'
import { notFound } from 'next/navigation'
import { AppShell } from '@/components/app-shell'
import { requireAdmin } from '@/lib/admin-auth'
import {
  archiveCompletedServiceCase, assignServiceOperator, createProviderRequest, createServiceEscalation,
  confirmServiceAppointment,
  recordProviderDecline, recordProviderOffer, resolveServiceEscalation,
  reviewAndPublishOptions, sendProviderRequest,
} from '@/lib/actions/service-operations'

export const dynamic = 'force-dynamic'
const input = 'w-full rounded-lg border bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus:outline-none'
const button = 'rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-45'

function value(object: unknown, key: string, fallback = 'Not provided') {
  if (!object || typeof object !== 'object' || Array.isArray(object)) return fallback
  const result = (object as Record<string, unknown>)[key]
  return result == null || result === '' ? fallback : String(result)
}

function money(amount: number | null) { return amount == null ? 'Not provided' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount) }
function dateTime(iso: string | null) { return iso ? new Date(iso).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' }) : 'Not proposed' }

export default async function ServiceCasePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const { admin, user } = await requireAdmin()
  const { data: serviceCase } = await admin.from('service_cases').select('*').eq('id', id).maybeSingle()
  if (!serviceCase) notFound()

  const [authorizations, requests, offers, messages, events, escalations, reviews, providers, verifications, operators, files, appointment, outcome] = await Promise.all([
    admin.from('service_authorizations').select('*').eq('service_case_id', id).order('approved_at', { ascending: false }),
    admin.from('provider_requests').select('*').eq('service_case_id', id).order('created_at'),
    admin.from('service_offers').select('*').eq('service_case_id', id).order('created_at'),
    admin.from('service_messages').select('*').eq('service_case_id', id).order('created_at'),
    admin.from('service_case_events').select('*').eq('service_case_id', id).order('created_at'),
    admin.from('service_escalations').select('*').eq('service_case_id', id).order('created_at', { ascending: false }),
    admin.from('service_quality_reviews').select('*').eq('service_case_id', id).order('created_at', { ascending: false }),
    admin.from('provider_businesses').select('*').eq('status', 'active').order('display_name'),
    admin.from('provider_verifications').select('*').eq('status', 'verified'),
    admin.from('profiles').select('id,name,email').eq('is_admin', true).order('name'),
    admin.from('service_case_files').select('file_id,approved_for_sharing,files(name,type)').eq('service_case_id', id),
    admin.from('service_appointments').select('*').eq('service_case_id', id).maybeSingle(),
    admin.from('service_outcomes').select('*').eq('service_case_id', id).maybeSingle(),
  ])
  const providerById = new Map((providers.data ?? []).map((row) => [row.id, row]))
  const verifiedContactIds = new Set((verifications.data ?? []).filter((row) => row.kind === 'contact').map((row) => row.provider_id))
  const activeShare = (authorizations.data ?? []).find((row) => row.kind === 'share_request' && row.status === 'active' && new Date(row.expires_at) > new Date())
  const canSource = ['sharing_approved','sourcing','awaiting_provider_responses'].includes(serviceCase.status) && Boolean(activeShare)
  const item = serviceCase.item_snapshot
  const address = serviceCase.service_address_snapshot

  return <AppShell showSearch={false}><div className="space-y-7">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/admin/service-cases" className="text-sm font-medium text-primary hover:underline">← Service queue</Link><h1 className="mt-2 font-serif text-3xl tracking-tight">{value(item, 'name', 'Service case')}</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">{serviceCase.symptom_summary ?? 'No symptom recorded'}</p></div><div className="text-right"><Status status={serviceCase.status}/><p className="mt-2 text-xs text-muted-foreground">Opened {dateTime(serviceCase.opened_at)}</p></div></header>

    <section className="grid gap-4 lg:grid-cols-[minmax(0,1.5fr)_minmax(280px,.7fr)]">
      <div className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Authorized case summary</h2><dl className="mt-4 grid gap-x-8 gap-y-4 sm:grid-cols-2"><Fact label="Manufacturer" value={value(item,'manufacturer')}/><Fact label="Model" value={value(item,'model')}/><Fact label="Serial" value={value(item,'serial')}/><Fact label="Service ZIP" value={value(address,'zip')}/><Fact label="Urgency" value={serviceCase.urgency}/><Fact label="Selected records" value={`${(files.data ?? []).filter((row) => row.approved_for_sharing).length}`}/></dl><p className="mt-5 border-t pt-4 text-xs text-muted-foreground">Street address is not included in the initial provider template. Operators may use only the current sharing scope.</p></div>
      <div className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Authorization and owner</h2>{activeShare ? <div className="mt-3"><p className="font-medium text-primary">Sharing approved</p><p className="text-sm text-muted-foreground">Expires {dateTime(activeShare.expires_at)}</p></div> : <div className="mt-3"><p className="font-medium text-destructive">No active sharing approval</p><p className="text-sm text-muted-foreground">Provider outreach is blocked.</p></div>}
        <form action={assignServiceOperator} className="mt-5 space-y-2"><input type="hidden" name="caseId" value={id}/><label className="block text-xs font-medium text-muted-foreground" htmlFor="operatorId">Operations owner</label><div className="flex gap-2"><select id="operatorId" name="operatorId" defaultValue={serviceCase.assigned_operator_id ?? user.id} className={input}>{(operators.data ?? []).map((row) => <option key={row.id} value={row.id}>{row.name ?? row.email}</option>)}</select><button className="rounded-lg border px-3 text-sm font-medium">Assign</button></div></form>
      </div>
    </section>

    {appointment.data && <section className="rounded-xl border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-semibold">Appointment coordination</h2><p className="mt-1 text-sm text-muted-foreground">The household approved these exact terms. Keep it pending until the provider confirms.</p></div><Status status={appointment.data.status}/></div><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Fact label="Window" value={`${dateTime(appointment.data.window_start)} – ${dateTime(appointment.data.window_end)}`}/><Fact label="Provider" value={providerById.get(appointment.data.provider_id)?.display_name ?? 'Provider'}/><Fact label="Cancellation" value={appointment.data.cancellation_terms_snapshot ?? 'Not provided'}/><Fact label="Reference" value={appointment.data.external_reference ?? 'Pending provider confirmation'}/></dl>{appointment.data.status === 'pending' && <form action={confirmServiceAppointment} className="mt-5 flex flex-wrap items-end gap-3"><input type="hidden" name="caseId" value={id}/><label className="min-w-72 flex-1 text-xs font-medium text-muted-foreground">Provider confirmation reference<input name="externalReference" required className={`${input} mt-1`} placeholder="Confirmation number or provider message ID"/></label><button className={button}>Record provider confirmation</button></form>}</section>}

    {outcome.data && <section className="rounded-xl border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-semibold">Homeowner-confirmed outcome</h2><p className="mt-1 text-sm text-muted-foreground">Private provider feedback stays in operations and is not presented as a public review.</p></div><Status status={outcome.data.resolution}/></div><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Fact label="Work performed" value={outcome.data.work_performed}/><Fact label="Final cost" value={money(outcome.data.final_cost)}/><Fact label="Parts" value={outcome.data.parts_summary ?? 'None recorded'}/><Fact label="Warranty" value={outcome.data.labor_warranty ?? 'None recorded'}/><Fact label="Timeliness" value={outcome.data.provider_timeliness ? `${outcome.data.provider_timeliness}/5` : 'Not rated'}/><Fact label="Communication" value={outcome.data.provider_communication ? `${outcome.data.provider_communication}/5` : 'Not rated'}/><Fact label="Visit date" value={outcome.data.occurred_on}/><Fact label="Care record" value={outcome.data.care_event_id ? 'Created' : 'Missing'}/></dl>{outcome.data.private_feedback && <p className="mt-4 rounded-lg bg-secondary/50 p-3 text-sm"><span className="font-medium">Private feedback:</span> {outcome.data.private_feedback}</p>}{serviceCase.status === 'completed' && <form action={archiveCompletedServiceCase} className="mt-5"><input type="hidden" name="caseId" value={id}/><button className={button}>Review and archive case</button></form>}</section>}

    <section className="rounded-xl border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Provider outreach</h2><p className="text-sm text-muted-foreground">Create from verified providers, then review the locked version-1 request before recording it as sent.</p></div><Link href="/admin/providers" className="text-sm font-medium text-primary hover:underline">Manage providers</Link></div>
      {!canSource && <div className="mt-4 rounded-lg bg-secondary/60 p-3 text-sm">Outreach is blocked until this case has active sharing approval and a sourcing-compatible state.</div>}
      {canSource && <form action={createProviderRequest} className="mt-5 grid gap-3 sm:grid-cols-[1fr_180px_auto]"><input type="hidden" name="caseId" value={id}/><label className="sr-only" htmlFor="providerId">Provider</label><select id="providerId" name="providerId" required className={input} defaultValue=""><option value="" disabled>Select verified provider</option>{(providers.data ?? []).filter((row) => verifiedContactIds.has(row.id)).map((row) => <option key={row.id} value={row.id}>{row.display_name}</option>)}</select><label className="sr-only" htmlFor="channel">Channel</label><select id="channel" name="channel" className={input}><option value="phone">Phone</option><option value="sms">SMS</option><option value="email">Email</option><option value="booking_link">Booking link</option></select><button className={button}>Prepare request</button></form>}
      <div className="mt-5 divide-y">{(requests.data ?? []).map((request) => { const provider = providerById.get(request.provider_id); return <div key={request.id} className="py-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">{provider?.display_name ?? 'Provider'}</p><p className="text-sm text-muted-foreground">{request.channel} · {request.status.replaceAll('_',' ')}</p></div>{request.status === 'approved_to_send' && <form action={sendProviderRequest}><input type="hidden" name="requestId" value={request.id}/><button className={button}>Record template sent</button></form>}</div>{['sent','viewed','responded'].includes(request.status) && <OfferForm requestId={request.id}/>} {['sent','viewed'].includes(request.status) && <form action={recordProviderDecline} className="mt-3 flex flex-wrap items-end gap-2"><input type="hidden" name="requestId" value={request.id}/><label className="min-w-64 flex-1 text-xs font-medium text-muted-foreground">Decline reason<input name="declineReason" required className={`${input} mt-1`} placeholder="Outside service area, brand unsupported…"/></label><button className="rounded-lg border px-3 py-2 text-sm font-medium">Record decline</button></form>}</div>})}{(requests.data ?? []).length === 0 && <p className="py-6 text-sm text-muted-foreground">No provider requests prepared.</p>}</div>
    </section>

    <section className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Normalized provider options</h2><p className="mt-1 text-sm text-muted-foreground">“Proposed” means the provider supplied the window. Only a non-empty confirmed timestamp supports confirmed-availability language.</p><div className="mt-5 grid gap-4 lg:grid-cols-2">{(offers.data ?? []).map((offer) => { const request = (requests.data ?? []).find((row) => row.id === offer.provider_request_id); const provider = request ? providerById.get(request.provider_id) : null; return <article key={offer.id} className="rounded-lg border p-4"><div className="flex items-start justify-between gap-3"><h3 className="font-semibold">{provider?.display_name ?? 'Provider option'}</h3><span className="text-xs font-medium text-muted-foreground">{offer.confirmed_at ? 'Provider-confirmed proposal' : 'Unconfirmed proposal'}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Fact label="Window" value={`${dateTime(offer.window_start)} – ${dateTime(offer.window_end)}`}/><Fact label="Diagnostic fee" value={money(offer.diagnostic_fee)}/><Fact label="Travel fee" value={money(offer.travel_fee)}/><Fact label="Visit" value={offer.visit_type.replaceAll('_',' ')}/></dl>{offer.provider_question && <p className="mt-4 rounded-lg bg-secondary/50 p-3 text-sm">Provider question: {offer.provider_question}</p>}</article>})}{(offers.data ?? []).length === 0 && <p className="text-sm text-muted-foreground">No normalized offers yet.</p>}</div>
      {serviceCase.status === 'awaiting_provider_responses' && <QualityReview caseId={id}/>} {(reviews.data ?? []).length > 0 && <p className="mt-4 text-xs text-muted-foreground">Latest review: {reviews.data![0].decision.replaceAll('_',' ')} · {dateTime(reviews.data![0].created_at)}</p>}
    </section>

    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Communication timeline</h2><ol className="mt-4 divide-y">{(messages.data ?? []).map((message) => <li key={message.id} className="py-3"><div className="flex justify-between gap-3 text-xs text-muted-foreground"><span>{message.direction} · {message.channel}{message.template_key ? ` · ${message.template_key} v${message.template_version}` : ''}</span><span>{dateTime(message.created_at)}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed">{message.redacted_body ?? message.body ?? 'No message body'}</p></li>)}{(messages.data ?? []).length === 0 && <li className="py-6 text-sm text-muted-foreground">No communications logged.</li>}</ol></div>
      <div className="space-y-4"><div className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Escalation</h2><form action={createServiceEscalation} className="mt-4 grid gap-3"><input type="hidden" name="caseId" value={id}/><div className="grid grid-cols-2 gap-3"><select name="kind" className={input}><option value="provider_question">Provider question</option><option value="response_overdue">Response overdue</option><option value="quality_review">Quality review</option><option value="safety_review">Safety review</option><option value="other">Other</option></select><select name="priority" className={input}><option value="normal">Normal</option><option value="urgent">Urgent</option><option value="immediate">Immediate</option></select></div><textarea name="summary" required placeholder="What needs attention, and what is the next safe action?" className={`${input} min-h-24`}/><button className={button}>Create escalation</button></form>{(escalations.data ?? []).filter((row) => row.status === 'open').map((row) => <div key={row.id} className="mt-3 rounded-lg bg-secondary/50 p-3 text-sm"><span className="font-medium">{row.priority} · {row.kind.replaceAll('_',' ')}</span><p className="mt-1 text-muted-foreground">{row.summary}</p><form action={resolveServiceEscalation} className="mt-2"><input type="hidden" name="escalationId" value={row.id}/><button className="text-xs font-semibold text-primary hover:underline">Mark resolved</button></form></div>)}</div>
        <div className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Audit history</h2><ol className="mt-4 space-y-3">{(events.data ?? []).map((event) => <li key={event.id} className="text-sm"><div className="font-medium">{event.prior_status ? `${event.prior_status.replaceAll('_',' ')} → ` : ''}{event.next_status.replaceAll('_',' ')}</div><div className="text-xs text-muted-foreground">{event.reason ?? event.actor_type} · {dateTime(event.created_at)}</div></li>)}</ol></div></div>
    </section>
  </div></AppShell>
}

function Status({ status }: { status: string }) { return <span className="inline-flex rounded-full bg-secondary px-3 py-1 text-sm font-semibold">{status.replaceAll('_',' ')}</span> }
function Fact({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-medium text-muted-foreground">{label}</dt><dd className="mt-1 break-words text-sm font-medium">{value}</dd></div> }

function OfferForm({ requestId }: { requestId: string }) { return <details className="mt-4 rounded-lg bg-secondary/35 p-4"><summary className="cursor-pointer text-sm font-semibold">Record provider response and offer</summary><form action={recordProviderOffer} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="requestId" value={requestId}/><label className="sm:col-span-2 text-xs font-medium">Exact provider response<textarea name="responseText" required className={`${input} mt-1 min-h-24`} placeholder="Record what the provider said. Do not add assumptions."/></label><label className="text-xs font-medium">Visit type<select name="visitType" className={`${input} mt-1`}><option value="diagnostic">Diagnostic</option><option value="estimate">Estimate</option><option value="repair_attempt">Repair attempt</option></select></label><label className="text-xs font-medium">Availability source<select name="availabilitySource" className={`${input} mt-1`}><option value="provider_statement">Provider statement</option><option value="operator_call">Operator call</option><option value="booking_link">Booking link</option></select></label><label className="text-xs font-medium">Proposed start<input type="datetime-local" name="windowStart" className={`${input} mt-1`}/></label><label className="text-xs font-medium">Proposed end<input type="datetime-local" name="windowEnd" className={`${input} mt-1`}/></label><label className="text-xs font-medium">Diagnostic fee<input name="diagnosticFee" type="number" min="0" step="0.01" className={`${input} mt-1`}/></label><label className="text-xs font-medium">Travel fee<input name="travelFee" type="number" min="0" step="0.01" className={`${input} mt-1`}/></label><label className="text-xs font-medium">Deposit<input name="deposit" type="number" min="0" step="0.01" className={`${input} mt-1`}/></label><label className="text-xs font-medium">Price notes<input name="priceNotes" className={`${input} mt-1`}/></label><label className="text-xs font-medium">Cancellation terms<input name="cancellationTerms" className={`${input} mt-1`}/></label><label className="text-xs font-medium">Parts / labor warranty<input name="partsLaborWarranty" className={`${input} mt-1`}/></label><label className="sm:col-span-2 text-xs font-medium">Provider question<input name="providerQuestion" className={`${input} mt-1`}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="tradeFit"/> Provider confirmed trade fit</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="confirmed"/> Provider confirmed this proposal</label><label className="text-xs font-medium">Proposal expires<input type="datetime-local" name="expiresAt" className={`${input} mt-1`}/></label><button className={`${button} sm:col-span-2`}>Save normalized offer</button></form></details> }

function QualityReview({ caseId }: { caseId: string }) { return <form action={reviewAndPublishOptions} className="mt-6 rounded-lg border p-4"><input type="hidden" name="caseId" value={caseId}/><h3 className="font-semibold">Quality review before publishing</h3><p className="mt-1 text-sm text-muted-foreground">Approval makes options visible to the household in A4. Confirm every statement is supported.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><label className="flex gap-2 text-sm"><input type="checkbox" name="verifiedProviders"/> Providers and contacts verified</label><label className="flex gap-2 text-sm"><input type="checkbox" name="comparableTerms"/> Fees and visit types normalized</label><label className="flex gap-2 text-sm"><input type="checkbox" name="honestAvailability"/> Availability wording matches evidence</label><label className="flex gap-2 text-sm"><input type="checkbox" name="sensitiveDataChecked"/> Sensitive data scope checked</label></div><textarea name="notes" className={`${input} mt-4 min-h-20`} placeholder="Review notes"/><div className="mt-3 flex gap-2"><button name="decision" value="approved" className={button}>Approve and publish options</button><button name="decision" value="changes_required" className="rounded-lg border px-4 py-2 text-sm font-medium">Request changes</button></div></form> }
